#!/bin/bash

rm -rf CMakeFiles/ android_gradle_build.json cmake_install.cmake CMakeCache.txt Makefile iperf3 libiperf3.so

cmake -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI="armeabi-v7a" ..
#cmake -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI="arm64-v8a" ..
#cmake -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI="x86" ..

make

echo "output:"
if [ -e iperf3 ]; then
  file iperf3
fi
if [ -e libiperf3.so ]; then
  file libiperf3.so
fi